### ISSUE TITLE
switch from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by ktdreyer** [release-engineering/kobo#159]
Recommend that we switch to GitHub Actions and rotate the encrypted `password` value in `.travis.yml` in light of https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/

**Comment by rohanpm** [comment]
The token in .travis.yml has already been revoked (not rotated - so the Travis-based release workflow is simply broken now).
+1 on moving to Actions, this has been planned for a while already.

**Comment by frenzymadness** [comment]
Hello.

I can help with this. I think we need to:
* switch to Github actions – we can use https://github.com/fedora-python/fedora-python-tox/actions because, in Fedora, we have the latest Python sooner than other CI systems have and Fedora is also close to the RHEL.
* drop support for Python 3.4 and 3.5 - I think we should test versions 3.6 (main Python in RHEL 8), 3.8 (module in RHEL 8), 3.9 (module in RHEL 8, main Python in RHEL 9) and 3.10 - the latest one.
* drop support for Django 1. We should test version 2.2 (still supported LTS, available in EPEL 8), 3.2 (current LTS version, available in Fedora) and 4 to be ready for the future LTS version.
* and of course fix all the problems this migration discovers.

One big question remains – do we want to keep Python 2 compatibility?

**Comment by rohanpm** [comment]
I don't want to aggressively rip out Python 2 support or intentionally make the code not work on Python 2, but if refactoring the CI I think it would be acceptable for the updated CI to not cover Python 2.

**Comment by kdudka** [comment]
@rohanpm Are you aware of anybody using up2date kobo with Python 2?  RHEL-7 instances of Covscan use `kobo-0.8.0`.  RHEL-8 instances of Covscan use Python 3.6.  If there are no users of kobo running on Python 2 any more and there is no CI coverage, the support for Python 2 will break sooner or later anyway.

**Comment by rohanpm** [comment]
@kdudka using upstream kobo releases on py2 - no.  My own team still has to backport recent kobo patches onto a RHEL6 build every now and then however, which at the moment usually are clean cherry-picks.

It's no big deal if new kobo code only works on py3, but for existing code which might still need fixes backported to legacy systems I don't want invasive changes such as "let's upgrade all the syntax to py3-only".

**Comment by kdudka** [comment]
@rohanpm That makes perfect sense to me.  Thank you for clarifying it!

**Comment by frenzymadness** [comment]
Thanks for making it clear. Your explanation makes perfect sense. I'll try to keep the code compatible with Python 2.
