### ISSUE TITLE
kobo-0.5.1 tag missing

### ISSUE THREAD

**Issue by kdudka** [release-engineering/kobo#18]
There is no ```kobo-0.5.1``` git tag despite such version of kobo was released in Fedora.  It is also not clear to me why the last version is tagged ```0.5.2``` instead of ```kobo-0.5.2``` as all the previous releases. Please keep the release tags consistent.

**Comment by dmach** [comment]
The missing tags are fixed.

I've changed the tagging schema because of github.
When you download an archive for kobo-0.5.2 tag, you end up with  kobo-kobo-0.5.2.tar.gz and identically named directory in the archive. It makes RPM packaging more painful since it doesn't follow the %name-%version schema.
