### ISSUE TITLE
Should deleting a worker also remove all its related tasks?

### ISSUE THREAD

**Issue by siteshwar** [release-engineering/kobo#224]
The [worker field](https://github.com/release-engineering/kobo/blob/efc22d7c292a92c8595cc2abad4e3240c9264575/kobo/hub/models.py#L552) in `Task` table is configured to `on_delete=models.CASCADE`, which means deleting a worker from database will delete all its related tasks. This could cause problems if we want to delete dynamically spun up workers on scale (similar to issue https://github.com/openscanhub/openscanhub/issues/82). Either we need to keep stale entries of unused workers in `Worker` table or we may have to workaround this in applications that depend on kobo.

I propose the `worker` field in `Task` table should be set to `NULL` when it's corresponding worker is deleted. Can this change cause any issues with projects that already depend on Kobo?

**Comment by rohanpm** [comment]
These probably should not be `CASCADE`.  I believe it's set that way because that was the default behavior in Django 1.x.  When porting to Django 2.0, per https://docs.djangoproject.com/en/2.2/releases/1.9/#foreignkey-and-onetoonefield-on-delete-argument `on_delete` became mandatory, and the value chosen was the same as the prior default so that there was no change in behavior.

The proposal makes sense to me and it's safer than the current behavior.

**Comment by lzaoral** [comment]
In that case, it may be handy to go through a list of all `ForeignKey` fields in `kobo` to see if the `on_delete=models.CASCADE` is really the desired behaviour.

**Comment by lzaoral** [comment]
@kdudka Note that analysing the source code as I suggested does not mean that it must be necessarily and immediately changed.
