### ISSUE TITLE
kobo tasks might be blocked forever

### ISSUE THREAD

**Issue by kdudka** [release-engineering/kobo#260]
As pointed out by @lzaoral, kobo tasks that produce output on their stdout/stderr might be blocked forever if the [logging thread](https://github.com/release-engineering/kobo/blob/d4b1c22d9bd35751a909ac40bdd736b3a1e1d54c/kobo/worker/taskmanager.py#L422) is killed and its [queue](https://github.com/release-engineering/kobo/blob/d4b1c22d9bd35751a909ac40bdd736b3a1e1d54c/kobo/worker/logger.py#L24) becomes full.

**Comment by rohanpm** [comment]
Can we clarify the "logging thread is killed" scenario?

If this refers to the "Fatal error in LoggingThread" path where an exception is allowed to propagate from the thread's main loop: I guess this can be fixed by having that path adjust self such that any later calls to the `write` method  will discard the data rather than putting it on the queue.
