### ISSUE TITLE
merge python 3 branch

### ISSUE THREAD

**Issue by ktdreyer** [release-engineering/kobo#31]
When can the `python-3-dev` branch merge to master and land in a point release?

**Comment by tkdchen** [comment]
Same question here.

**Comment by frenzymadness** [comment]
Hello.

`python-3-dev` seems to be old and it contains changes which break backward compatibility with Python 2.6 so I started with porting Kobo to Python 3 from scratch.

First I'll improve tox configuration and I'll add Travis CI config to test every PR and then I'll start with porting (Syntax errors first).

If you want to help, improving test coverage would be very useful because tests can prevent bugs during porting.

**Comment by ktdreyer** [comment]
Thanks @frenzymadness , that's great. I have been running the `python-3-dev` branch in Travis CI for several months now in order to get py3 compatibility for one of my applications that uses `kobo.conf`, so I will be really interested in this.

**Comment by frenzymadness** [comment]
Hi @ktdreyer and @tkdchen 

I've created WIP PR with my Python 3 related changes. It would be great if you could help me with testing and improving test coverage.

See: https://github.com/release-engineering/kobo/pull/48

**Comment by frenzymadness** [comment]
Mentioned PR is merged so we can close this issue.

**Comment by rohanpm** [comment]
The changes for python 3 compatibility were released in kobo 0.7.0.
