### ISSUE TITLE
cancel_subtasks fails to cancel subtasks

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/kobo#89]
The method `cancel_subtasks` has the following line:

```python
result &= task.cancel_task()
```

`cancel_task` does not return a boolean, actually, it does not return anything.

This causes the error:

    TypeError: unsupported operand type(s) for &=: 'bool' and 'NoneType'

**Comment by rohanpm** [comment]
I suggest the fix here may be simply deleting the cancel_subtasks method, since it seems that 100% of calls to the method would have been crashing up to now.

**Comment by rohanpm** [comment]
I withdraw my earlier suggestion for deleting the method, because actually the method would have "worked" if a parent task has dangling or duplicate references to subtasks - the method seems designed specifically for that.

Since subtasks have been rarely used, I don't have any good sense of whether it's likely someone could really depend on that, making it a bit risky to assume it's safe to delete.
